### PR TITLE
Textures

### LINKED ISSUE #3: Missing textures and texture adjustments
Missing textures:

- wooden planks
- shadow cobblestone

Texture changes needed:

- the side of the plant/flower needs adjustment
- top of tree trunk is too yellow and needs some detail

### PR DESCRIPTION
**Pull request by ghost**
Contains:

shadow_stone. [Improved the sharp edges]
shadow_cobble.

shadow_grass.

shadow_grass_side.
shadow_grass_top.

shadow_tree_sapling.
shadow_tree_top. [Added more details]
shadow_tree_side.
shadow_tree_leaves. [Less bright and slight variable colors of leaves]
shadow_fruit.
shadow_fruit_open.
shadow_wood_plank.
suntwist_plant. [Removed the side flowers]

Fixes #3

### CODE REVIEW

**Comment by Ezhh** [comment]
For suntwist, I've actually made a slightly edited version of the original that I really like. Could we get the new version as a separate texture? I think having both could add some really nice variation.

Cobble and planks look great. :)
(Though do we need to match the plank colour more to the inside wood colour? We can use the current texture for something else if so.)

I'll need to compare the stone/grass in game with the originals - but note that the grass side texture has a misplaced pixel on the bottom. I removed this on the current one.

**Comment by ghost** [comment]
Got it. 

Yes we can have both. :)

With plank, I did try to to make it close to the inner wood but couldn't make it look good with the gold/yellow ish color. Should I give it some more try (promise not to disappear for month(s) :P) ? 

The stone just has a bit more kind of fade between each stone drawings (not node). The grass is not changed, I am just stupid and added everything. Same problem of adding everything, with grass side (there is no new work).

List of thing that are already in the repository, and have no change/improvements in the pull request:

shadow_grass.
shadow_grass_side.
shadow_grass_top.

**Comment by Ezhh** [comment]
Okay, can we drop the ones that are unchanged from the PR, and make the new suntwist have a separate name? Then I think we can hit the merge button :D

I'd say leave the planks as is for now. You are quite welcome to work on a second texture as well, but I'll happily take both if so. :)

When you can chat on IRC more, I can catch you up with some things.

**Comment by ghost** [comment]
Sounds good. :)

Yes, will be on IRC soon, just have to fix some things (Matrix is being weird; direct messages don't seem to go through, and don't want to log in with my IP visible). :)

**Comment by Ezhh** [comment]
No worries, and take your time. Just very happy to see you around again.

**Comment by ghost** [comment]
:bowing_man:

**Comment by Ezhh** [comment]
You okay?

**Comment by ghost** [comment]
Yes, sorry, I am kind of slow doing this. :D 
I made new request with unchanged textures removed and the plant name changed. :)

**Pull request closed without merging**
